### PR TITLE
Cross-build to Scala 2.13.0-RC1

### PR DESCRIPTION
**Pull request by dwijnand**
Builds on #230
Needs a release of Slick for 2.13.0-RC1.

### CODE REVIEW

**Comment by WellingR** [comment]
As long as the new slick version has not yet been released yet, this will not build, so perhaps we should keep this PR open until we are sure we can get it to work.

**Comment by dwijnand** [comment]
Yeah, it's passing because it's not being tested.  I'll push the CI update and then we can wait for Slick.

**Comment by dwijnand** [comment]
That's more like it

```
unresolved dependency: com.typesafe.slick#slick-hikaricp_2.13.0-RC1;3.3.0: not found
```

**Comment by dwijnand** [comment]
Let's pick this one up when Slick moves forward.

**Pull request closed without merging**
