### PR TITLE
Provide support for MS-SQL-server

### PR DESCRIPTION
**Pull request by naferx**
Ref #102

### CODE REVIEW

**Comment by naferx** [comment]
Hi @dnvriend , How can I set up environment variables for MS SqlServer ?
Seems like Travis is hanging out for it

**Comment by dnvriend** [comment]
@naferx AFAIK configuring Travis is something that only the account holder (me) can do, but I've added the environment vars. A question, I cannot find sqlserver support in the docs for Travis? Where did you find the configuration as you've edited travis.yml?

**Comment by naferx** [comment]
Oh sorry, I thought that editing the file, it could work. Let me a moment to revert that change

**Comment by naferx** [comment]
I'm wondering why the tests didn't run :confused:
```
[info] - should persist a single serializable message (785 milliseconds)
[info] - should not persist a single non-serializable message (516 milliseconds)
[info] - should persist only serializable messages (711 milliseconds)
[info] SqlServerStoreOnlySerializableMessagesTest:


No output has been received in the last 10m0s, this potentially indicates a 
stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on:
 https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
```

**Comment by WellingR** [comment]
If I take a look at the readme on the [slick github repo](https://github.com/slick/slick ). Then you can see that the slick build for MS SQL server is actually built using [Appveyor](https://ci.appveyor.com/project/slick/slick).

We might need to investigate if we can set this up for the SQL server build

**Comment by naferx** [comment]
@WellingR , Thanks for the hint

I've been busy these days, hope to investigate how to do that setup on next weekend.

**Comment by WellingR** [comment]
There seems to be a new docker release for sql server 2017. So it might be worth investigating if it possible to get this one to work with travis

**Comment by PerWiklander** [comment]
Is the status of this that we are waiting for working CI, while the actual feature is ready for use (more or less)?

**Comment by WellingR** [comment]
@PerWiklander Assuming that the PR autor managed to run the tests locally, you are correct.

@naferx Are you still planning to continue working on this soon, or do you want some help?

**Comment by naferx** [comment]
@PerWiklander, I tested it locally based on https://github.com/akka/akka-samples/tree/2.5/akka-sample-persistence-scala

@WellingR, I was trying to setup appyevor on this repo test https://github.com/naferx/akka-persistence-jdbc-test, but don't have enough time. At this point, I have to let someone else continue

**Comment by renatocaval** [comment]
@naferx are you still interesting in pursuing with this PR? It is now in conflict and we still need to sort out the build. Have you tried to get it running with a docker like @WellingR suggested? That might be the best option because all other tests are running with docker already and it's easier if we keep the build in Travis.

**Comment by naferx** [comment]
Ohh, Sorry Renato,
Unfortunately, I don't have enough time to push it over the finish line.
I hope someone can continue my initial effort.

On Thu, Apr 26, 2018 at 8:56 AM, Renato Cavalcanti <notifications@github.com

**Comment by renatocaval** [comment]
@naferx, I will be closing this for now. Nobody else in the community seems to have a need for it. If you don't delete your original branch, someone can maybe pickup from there or get inspiration from it.

Thanks for you efforts in any case.

**Pull request closed without merging**
