### PR TITLE
Build for Scala 2.13.0-RC2

### PR DESCRIPTION
**Pull request by renatocaval**

### CODE REVIEW

**Comment by renatocaval** [comment]
This won't build for now. Slick 3.3.1 is being published to maven central

**Comment by renatocaval** [comment]
@WellingR, this one is green. I would like to cut a release (RC) so we can move on in Lagom.

**Comment by renatocaval** [comment]
Maybe we should cut a 3.5.1 with artefacts for Scala 2.13.0-RC2 instead of 3.6.0-RC1. I can backport it to 3.5.0 if decided so.

**Comment by renatocaval** [comment]
I just realised that there is now 3.5.x branch. We will cut 3.5.1 from master, so no backport needed.

**Comment by dwijnand** [comment]
Who can cut a release of akka-persistence-jdbc for Scala 2.13.0-RC2?  @renatocaval can you?

**Pull request merged**
