### PR TITLE
Update Akka (2.5), Slick (3.2.1) and Hikari (2.6)

### PR DESCRIPTION
**Pull request by sarahgerweck**
* Update Akka to 2.5(.3). Akka 2.5 drops the old persistence APIs and
    finalizes on the new interfaces. Akka maintains binary compatibility, so
    this should be compatible with all 2.5.x releases.
  * Update Slick to 3.2.1, which is *not* binary compatible with Slick 3.2
  * Update HikariCP version to 2.6. This should be transparent.

### CODE REVIEW

**Comment by sarahgerweck** [comment]
Will fix tests.

**Comment by WellingR** [comment]
First of all, thanks very much for contributing.

It should be noted that this project already has a separate branch for akka 2.5.
I am making the project ready for a next release which will probably happen in less than one week. The akka 2.5 branch will probably become the master branch at this point. I will make sure that these dependency updated will be included.

**Comment by rcavalcanti** [comment]
Hi @WellingR, I was working on that as well. I have it ready here, but build on 2.5.x.x branch. I will send a PR, feel free to decline if you have it ready on your machine

**Comment by sarahgerweck** [comment]
@WellingR Akka 2.5 is binary compatible with Akka 2.4, so the bigger urgency for update is Slick 3.2.1. Akka-Persistence-JDBC relies on Slick APIs that are not binary compatible, so this library can't be simultaneously compatible with Slick 3.2.0 and Slick 3.2.1.

**Comment by WellingR** [comment]
@sarahgerweck Since akka-persistence-query was experimental in Akka 2.4.
Akka 2.4 and 2.5 are actually not binary compatible for this plugin.

Nonetheless. I have merged the 2.5.0.0 branch with master, and created a separate branch for akka 2.4 the dependency updates have been included.

I will add a note in the release notes stating the binary incompatibility of slick 3.2.1.

Thanks for your contribution, I will close this PR.

**Pull request closed without merging**
