### PR TITLE
Making base64 encoding/decoding optional

### PR DESCRIPTION
**Pull request by arminc**
I am storing my messages as Json in to the database and I didn't want them to be base64 so I made it optional.

### CODE REVIEW

**Comment by prettynatty** [comment]
It also would be great to have ability to store messages in column with BLOB type (bytea in postgres for example).

**Comment by t3hnar** [comment]
hi, @dnvriend are you going to merger this?

**Comment by dnvriend** [comment]
This week I will look at all the pull requests. The serialization feature is something I want to have for some time now, but I am thinking about a pluggable architecture, so this pull request will not be it but I will look into it. I am glad that you contributed though and your code will serve for inspiration. Thank you! 

Regards

Dennis

**Comment by t3hnar** [comment]
Thanks, just wanted to add some feature that are nice to have:
* ability to change `journal`/`snapshot` tables schema and mapping
* it should be easy to store data in readable formats (json, xml, etc..)

Really looking forward to your new release :)

**Pull request closed without merging**
