### PR TITLE
upgrade from SBT 0.13.x to SBT 1.1.1

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by WellingR** [comment]
Thanks for this. I will do a test sometime soon to verify that the sbt-bintray integration still works

**Comment by sullis** [comment]
ping @WellingR

**Comment by WellingR** [comment]
Been busy lately. I probably will not have the time to test this the next two weeks, but I will make sure this is merged before the next release of akka-persistence-jdbc

**Comment by sullis** [comment]
cool, thx

**Pull request merged**
